// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoiceapplication type in the database.
	Label = "invoice_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderIds holds the string denoting the order_ids field in the database.
	FieldOrderIds = "order_ids"
	// FieldOrderNos holds the string denoting the order_nos field in the database.
	FieldOrderNos = "order_nos"
	// FieldNeedPayTax holds the string denoting the need_pay_tax field in the database.
	FieldNeedPayTax = "need_pay_tax"
	// FieldTaxOrderNos holds the string denoting the tax_order_nos field in the database.
	FieldTaxOrderNos = "tax_order_nos"
	// FieldValidationSnapshot holds the string denoting the validation_snapshot field in the database.
	FieldValidationSnapshot = "validation_snapshot"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldRecipientEmail holds the string denoting the recipient_email field in the database.
	FieldRecipientEmail = "recipient_email"
	// FieldTotalAmount holds the string denoting the total_amount field in the database.
	FieldTotalAmount = "total_amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldExternalSnapshot holds the string denoting the external_snapshot field in the database.
	FieldExternalSnapshot = "external_snapshot"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the invoiceapplication in the database.
	Table = "invoice_applications"
)

// Columns holds all SQL columns for invoiceapplication fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOrderIds,
	FieldOrderNos,
	FieldNeedPayTax,
	FieldTaxOrderNos,
	FieldValidationSnapshot,
	FieldExternalID,
	FieldStatus,
	FieldTitle,
	FieldRecipientEmail,
	FieldTotalAmount,
	FieldCurrency,
	FieldExternalSnapshot,
	FieldRequestID,
	FieldErrorCode,
	FieldErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOrderIds holds the default value on creation for the "order_ids" field.
	DefaultOrderIds func() []int64
	// DefaultOrderNos holds the default value on creation for the "order_nos" field.
	DefaultOrderNos func() []string
	// DefaultNeedPayTax holds the default value on creation for the "need_pay_tax" field.
	DefaultNeedPayTax bool
	// DefaultTaxOrderNos holds the default value on creation for the "tax_order_nos" field.
	DefaultTaxOrderNos func() []string
	// DefaultValidationSnapshot holds the default value on creation for the "validation_snapshot" field.
	DefaultValidationSnapshot func() map[string]interface{}
	// ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	ExternalIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// RecipientEmailValidator is a validator for the "recipient_email" field. It is called by the builders before save.
	RecipientEmailValidator func(string) error
	// DefaultTotalAmount holds the default value on creation for the "total_amount" field.
	DefaultTotalAmount string
	// TotalAmountValidator is a validator for the "total_amount" field. It is called by the builders before save.
	TotalAmountValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultExternalSnapshot holds the default value on creation for the "external_snapshot" field.
	DefaultExternalSnapshot func() map[string]interface{}
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNeedPayTax orders the results by the need_pay_tax field.
func ByNeedPayTax(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNeedPayTax, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByRecipientEmail orders the results by the recipient_email field.
func ByRecipientEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientEmail, opts...).ToFunc()
}

// ByTotalAmount orders the results by the total_amount field.
func ByTotalAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
