// Code generated by ent, DO NOT EDIT.

package invoiceapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// NeedPayTax applies equality check predicate on the "need_pay_tax" field. It's identical to NeedPayTaxEQ.
func NeedPayTax(v bool) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldNeedPayTax, v))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldExternalID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTitle, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRecipientEmail, v))
}

// TotalAmount applies equality check predicate on the "total_amount" field. It's identical to TotalAmountEQ.
func TotalAmount(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCurrency, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRequestID, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUserID, v))
}

// NeedPayTaxEQ applies the EQ predicate on the "need_pay_tax" field.
func NeedPayTaxEQ(v bool) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldNeedPayTax, v))
}

// NeedPayTaxNEQ applies the NEQ predicate on the "need_pay_tax" field.
func NeedPayTaxNEQ(v bool) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldNeedPayTax, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDIsNil applies the IsNil predicate on the "external_id" field.
func ExternalIDIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldExternalID))
}

// ExternalIDNotNil applies the NotNil predicate on the "external_id" field.
func ExternalIDNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldExternalID))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldExternalID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldStatus, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldTitle, v))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailIsNil applies the IsNil predicate on the "recipient_email" field.
func RecipientEmailIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRecipientEmail))
}

// RecipientEmailNotNil applies the NotNil predicate on the "recipient_email" field.
func RecipientEmailNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRecipientEmail))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// TotalAmountEQ applies the EQ predicate on the "total_amount" field.
func TotalAmountEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldTotalAmount, v))
}

// TotalAmountNEQ applies the NEQ predicate on the "total_amount" field.
func TotalAmountNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldTotalAmount, v))
}

// TotalAmountIn applies the In predicate on the "total_amount" field.
func TotalAmountIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldTotalAmount, vs...))
}

// TotalAmountNotIn applies the NotIn predicate on the "total_amount" field.
func TotalAmountNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldTotalAmount, vs...))
}

// TotalAmountGT applies the GT predicate on the "total_amount" field.
func TotalAmountGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldTotalAmount, v))
}

// TotalAmountGTE applies the GTE predicate on the "total_amount" field.
func TotalAmountGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldTotalAmount, v))
}

// TotalAmountLT applies the LT predicate on the "total_amount" field.
func TotalAmountLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldTotalAmount, v))
}

// TotalAmountLTE applies the LTE predicate on the "total_amount" field.
func TotalAmountLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldTotalAmount, v))
}

// TotalAmountContains applies the Contains predicate on the "total_amount" field.
func TotalAmountContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldTotalAmount, v))
}

// TotalAmountHasPrefix applies the HasPrefix predicate on the "total_amount" field.
func TotalAmountHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldTotalAmount, v))
}

// TotalAmountHasSuffix applies the HasSuffix predicate on the "total_amount" field.
func TotalAmountHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldTotalAmount, v))
}

// TotalAmountEqualFold applies the EqualFold predicate on the "total_amount" field.
func TotalAmountEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldTotalAmount, v))
}

// TotalAmountContainsFold applies the ContainsFold predicate on the "total_amount" field.
func TotalAmountContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldTotalAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldCurrency, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldRequestID, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceApplication) predicate.InvoiceApplication {
	return predicate.InvoiceApplication(sql.NotPredicates(p))
}
