// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/helpdocument"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// HelpDocument is the model entity for the HelpDocument schema.
type HelpDocument struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// ContentMarkdown holds the value of the "content_markdown" field.
	ContentMarkdown string `json:"content_markdown,omitempty"`
	// SelectorSchema holds the value of the "selector_schema" field.
	SelectorSchema map[string]interface{} `json:"selector_schema,omitempty"`
	// PublishedSnapshot holds the value of the "published_snapshot" field.
	PublishedSnapshot *domain.HelpDocumentSnapshot `json:"published_snapshot,omitempty"`
	// PublicationHistory holds the value of the "publication_history" field.
	PublicationHistory []domain.HelpDocumentSnapshot `json:"publication_history,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy *int64 `json:"updated_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HelpDocument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case helpdocument.FieldSelectorSchema, helpdocument.FieldPublishedSnapshot, helpdocument.FieldPublicationHistory:
			values[i] = new([]byte)
		case helpdocument.FieldID, helpdocument.FieldVersion, helpdocument.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case helpdocument.FieldSlug, helpdocument.FieldTitle, helpdocument.FieldCategory, helpdocument.FieldSummary, helpdocument.FieldContentMarkdown, helpdocument.FieldStatus:
			values[i] = new(sql.NullString)
		case helpdocument.FieldPublishedAt, helpdocument.FieldCreatedAt, helpdocument.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HelpDocument fields.
func (_m *HelpDocument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case helpdocument.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case helpdocument.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case helpdocument.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case helpdocument.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case helpdocument.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case helpdocument.FieldContentMarkdown:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_markdown", values[i])
			} else if value.Valid {
				_m.ContentMarkdown = value.String
			}
		case helpdocument.FieldSelectorSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selector_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectorSchema); err != nil {
					return fmt.Errorf("unmarshal field selector_schema: %w", err)
				}
			}
		case helpdocument.FieldPublishedSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field published_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PublishedSnapshot); err != nil {
					return fmt.Errorf("unmarshal field published_snapshot: %w", err)
				}
			}
		case helpdocument.FieldPublicationHistory:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field publication_history", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PublicationHistory); err != nil {
					return fmt.Errorf("unmarshal field publication_history: %w", err)
				}
			}
		case helpdocument.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case helpdocument.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case helpdocument.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case helpdocument.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		case helpdocument.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case helpdocument.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HelpDocument.
// This includes values selected through modifiers, order, etc.
func (_m *HelpDocument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HelpDocument.
// Note that you need to call HelpDocument.Unwrap() before calling this method if this HelpDocument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HelpDocument) Update() *HelpDocumentUpdateOne {
	return NewHelpDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HelpDocument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HelpDocument) Unwrap() *HelpDocument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HelpDocument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HelpDocument) String() string {
	var builder strings.Builder
	builder.WriteString("HelpDocument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("content_markdown=")
	builder.WriteString(_m.ContentMarkdown)
	builder.WriteString(", ")
	builder.WriteString("selector_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectorSchema))
	builder.WriteString(", ")
	builder.WriteString("published_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublishedSnapshot))
	builder.WriteString(", ")
	builder.WriteString("publication_history=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicationHistory))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// HelpDocuments is a parsable slice of HelpDocument.
type HelpDocuments []*HelpDocument
