// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/helpdocument"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// HelpDocumentUpdate is the builder for updating HelpDocument entities.
type HelpDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *HelpDocumentMutation
}

// Where appends a list predicates to the HelpDocumentUpdate builder.
func (_u *HelpDocumentUpdate) Where(ps ...predicate.HelpDocument) *HelpDocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *HelpDocumentUpdate) SetSlug(v string) *HelpDocumentUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableSlug(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HelpDocumentUpdate) SetTitle(v string) *HelpDocumentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableTitle(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *HelpDocumentUpdate) SetCategory(v string) *HelpDocumentUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableCategory(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HelpDocumentUpdate) SetSummary(v string) *HelpDocumentUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableSummary(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *HelpDocumentUpdate) ClearSummary() *HelpDocumentUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetContentMarkdown sets the "content_markdown" field.
func (_u *HelpDocumentUpdate) SetContentMarkdown(v string) *HelpDocumentUpdate {
	_u.mutation.SetContentMarkdown(v)
	return _u
}

// SetNillableContentMarkdown sets the "content_markdown" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableContentMarkdown(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetContentMarkdown(*v)
	}
	return _u
}

// SetSelectorSchema sets the "selector_schema" field.
func (_u *HelpDocumentUpdate) SetSelectorSchema(v map[string]interface{}) *HelpDocumentUpdate {
	_u.mutation.SetSelectorSchema(v)
	return _u
}

// ClearSelectorSchema clears the value of the "selector_schema" field.
func (_u *HelpDocumentUpdate) ClearSelectorSchema() *HelpDocumentUpdate {
	_u.mutation.ClearSelectorSchema()
	return _u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_u *HelpDocumentUpdate) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentUpdate {
	_u.mutation.SetPublishedSnapshot(v)
	return _u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (_u *HelpDocumentUpdate) ClearPublishedSnapshot() *HelpDocumentUpdate {
	_u.mutation.ClearPublishedSnapshot()
	return _u
}

// SetPublicationHistory sets the "publication_history" field.
func (_u *HelpDocumentUpdate) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpdate {
	_u.mutation.SetPublicationHistory(v)
	return _u
}

// AppendPublicationHistory appends value to the "publication_history" field.
func (_u *HelpDocumentUpdate) AppendPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpdate {
	_u.mutation.AppendPublicationHistory(v)
	return _u
}

// ClearPublicationHistory clears the value of the "publication_history" field.
func (_u *HelpDocumentUpdate) ClearPublicationHistory() *HelpDocumentUpdate {
	_u.mutation.ClearPublicationHistory()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HelpDocumentUpdate) SetStatus(v string) *HelpDocumentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableStatus(v *string) *HelpDocumentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *HelpDocumentUpdate) SetVersion(v int) *HelpDocumentUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableVersion(v *int) *HelpDocumentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *HelpDocumentUpdate) AddVersion(v int) *HelpDocumentUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *HelpDocumentUpdate) SetPublishedAt(v time.Time) *HelpDocumentUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillablePublishedAt(v *time.Time) *HelpDocumentUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *HelpDocumentUpdate) ClearPublishedAt() *HelpDocumentUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *HelpDocumentUpdate) SetUpdatedBy(v int64) *HelpDocumentUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *HelpDocumentUpdate) SetNillableUpdatedBy(v *int64) *HelpDocumentUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *HelpDocumentUpdate) AddUpdatedBy(v int64) *HelpDocumentUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *HelpDocumentUpdate) ClearUpdatedBy() *HelpDocumentUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HelpDocumentUpdate) SetUpdatedAt(v time.Time) *HelpDocumentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HelpDocumentMutation object of the builder.
func (_u *HelpDocumentUpdate) Mutation() *HelpDocumentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HelpDocumentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HelpDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HelpDocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HelpDocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HelpDocumentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := helpdocument.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HelpDocumentUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := helpdocument.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := helpdocument.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := helpdocument.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := helpdocument.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentMarkdown(); ok {
		if err := helpdocument.ContentMarkdownValidator(v); err != nil {
			return &ValidationError{Name: "content_markdown", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.content_markdown": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := helpdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.status": %w`, err)}
		}
	}
	return nil
}

func (_u *HelpDocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(helpdocument.Table, helpdocument.Columns, sqlgraph.NewFieldSpec(helpdocument.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(helpdocument.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(helpdocument.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(helpdocument.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(helpdocument.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(helpdocument.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ContentMarkdown(); ok {
		_spec.SetField(helpdocument.FieldContentMarkdown, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelectorSchema(); ok {
		_spec.SetField(helpdocument.FieldSelectorSchema, field.TypeJSON, value)
	}
	if _u.mutation.SelectorSchemaCleared() {
		_spec.ClearField(helpdocument.FieldSelectorSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedSnapshot(); ok {
		_spec.SetField(helpdocument.FieldPublishedSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.PublishedSnapshotCleared() {
		_spec.ClearField(helpdocument.FieldPublishedSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublicationHistory(); ok {
		_spec.SetField(helpdocument.FieldPublicationHistory, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicationHistory(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, helpdocument.FieldPublicationHistory, value)
		})
	}
	if _u.mutation.PublicationHistoryCleared() {
		_spec.ClearField(helpdocument.FieldPublicationHistory, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(helpdocument.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(helpdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(helpdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(helpdocument.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(helpdocument.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(helpdocument.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(helpdocument.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(helpdocument.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(helpdocument.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{helpdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HelpDocumentUpdateOne is the builder for updating a single HelpDocument entity.
type HelpDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HelpDocumentMutation
}

// SetSlug sets the "slug" field.
func (_u *HelpDocumentUpdateOne) SetSlug(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableSlug(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *HelpDocumentUpdateOne) SetTitle(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableTitle(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *HelpDocumentUpdateOne) SetCategory(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableCategory(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *HelpDocumentUpdateOne) SetSummary(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableSummary(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *HelpDocumentUpdateOne) ClearSummary() *HelpDocumentUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetContentMarkdown sets the "content_markdown" field.
func (_u *HelpDocumentUpdateOne) SetContentMarkdown(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetContentMarkdown(v)
	return _u
}

// SetNillableContentMarkdown sets the "content_markdown" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableContentMarkdown(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetContentMarkdown(*v)
	}
	return _u
}

// SetSelectorSchema sets the "selector_schema" field.
func (_u *HelpDocumentUpdateOne) SetSelectorSchema(v map[string]interface{}) *HelpDocumentUpdateOne {
	_u.mutation.SetSelectorSchema(v)
	return _u
}

// ClearSelectorSchema clears the value of the "selector_schema" field.
func (_u *HelpDocumentUpdateOne) ClearSelectorSchema() *HelpDocumentUpdateOne {
	_u.mutation.ClearSelectorSchema()
	return _u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_u *HelpDocumentUpdateOne) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentUpdateOne {
	_u.mutation.SetPublishedSnapshot(v)
	return _u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (_u *HelpDocumentUpdateOne) ClearPublishedSnapshot() *HelpDocumentUpdateOne {
	_u.mutation.ClearPublishedSnapshot()
	return _u
}

// SetPublicationHistory sets the "publication_history" field.
func (_u *HelpDocumentUpdateOne) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpdateOne {
	_u.mutation.SetPublicationHistory(v)
	return _u
}

// AppendPublicationHistory appends value to the "publication_history" field.
func (_u *HelpDocumentUpdateOne) AppendPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpdateOne {
	_u.mutation.AppendPublicationHistory(v)
	return _u
}

// ClearPublicationHistory clears the value of the "publication_history" field.
func (_u *HelpDocumentUpdateOne) ClearPublicationHistory() *HelpDocumentUpdateOne {
	_u.mutation.ClearPublicationHistory()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HelpDocumentUpdateOne) SetStatus(v string) *HelpDocumentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableStatus(v *string) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *HelpDocumentUpdateOne) SetVersion(v int) *HelpDocumentUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableVersion(v *int) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *HelpDocumentUpdateOne) AddVersion(v int) *HelpDocumentUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *HelpDocumentUpdateOne) SetPublishedAt(v time.Time) *HelpDocumentUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillablePublishedAt(v *time.Time) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *HelpDocumentUpdateOne) ClearPublishedAt() *HelpDocumentUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *HelpDocumentUpdateOne) SetUpdatedBy(v int64) *HelpDocumentUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *HelpDocumentUpdateOne) SetNillableUpdatedBy(v *int64) *HelpDocumentUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *HelpDocumentUpdateOne) AddUpdatedBy(v int64) *HelpDocumentUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *HelpDocumentUpdateOne) ClearUpdatedBy() *HelpDocumentUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HelpDocumentUpdateOne) SetUpdatedAt(v time.Time) *HelpDocumentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the HelpDocumentMutation object of the builder.
func (_u *HelpDocumentUpdateOne) Mutation() *HelpDocumentMutation {
	return _u.mutation
}

// Where appends a list predicates to the HelpDocumentUpdate builder.
func (_u *HelpDocumentUpdateOne) Where(ps ...predicate.HelpDocument) *HelpDocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HelpDocumentUpdateOne) Select(field string, fields ...string) *HelpDocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HelpDocument entity.
func (_u *HelpDocumentUpdateOne) Save(ctx context.Context) (*HelpDocument, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HelpDocumentUpdateOne) SaveX(ctx context.Context) *HelpDocument {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HelpDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HelpDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HelpDocumentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := helpdocument.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HelpDocumentUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := helpdocument.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := helpdocument.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := helpdocument.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := helpdocument.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentMarkdown(); ok {
		if err := helpdocument.ContentMarkdownValidator(v); err != nil {
			return &ValidationError{Name: "content_markdown", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.content_markdown": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := helpdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.status": %w`, err)}
		}
	}
	return nil
}

func (_u *HelpDocumentUpdateOne) sqlSave(ctx context.Context) (_node *HelpDocument, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(helpdocument.Table, helpdocument.Columns, sqlgraph.NewFieldSpec(helpdocument.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HelpDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, helpdocument.FieldID)
		for _, f := range fields {
			if !helpdocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != helpdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(helpdocument.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(helpdocument.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(helpdocument.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(helpdocument.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(helpdocument.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ContentMarkdown(); ok {
		_spec.SetField(helpdocument.FieldContentMarkdown, field.TypeString, value)
	}
	if value, ok := _u.mutation.SelectorSchema(); ok {
		_spec.SetField(helpdocument.FieldSelectorSchema, field.TypeJSON, value)
	}
	if _u.mutation.SelectorSchemaCleared() {
		_spec.ClearField(helpdocument.FieldSelectorSchema, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedSnapshot(); ok {
		_spec.SetField(helpdocument.FieldPublishedSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.PublishedSnapshotCleared() {
		_spec.ClearField(helpdocument.FieldPublishedSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublicationHistory(); ok {
		_spec.SetField(helpdocument.FieldPublicationHistory, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublicationHistory(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, helpdocument.FieldPublicationHistory, value)
		})
	}
	if _u.mutation.PublicationHistoryCleared() {
		_spec.ClearField(helpdocument.FieldPublicationHistory, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(helpdocument.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(helpdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(helpdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(helpdocument.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(helpdocument.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(helpdocument.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(helpdocument.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(helpdocument.FieldUpdatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(helpdocument.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &HelpDocument{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{helpdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
