// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/helpdocument"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// HelpDocumentDelete is the builder for deleting a HelpDocument entity.
type HelpDocumentDelete struct {
	config
	hooks    []Hook
	mutation *HelpDocumentMutation
}

// Where appends a list predicates to the HelpDocumentDelete builder.
func (_d *HelpDocumentDelete) Where(ps ...predicate.HelpDocument) *HelpDocumentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HelpDocumentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HelpDocumentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HelpDocumentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(helpdocument.Table, sqlgraph.NewFieldSpec(helpdocument.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HelpDocumentDeleteOne is the builder for deleting a single HelpDocument entity.
type HelpDocumentDeleteOne struct {
	_d *HelpDocumentDelete
}

// Where appends a list predicates to the HelpDocumentDelete builder.
func (_d *HelpDocumentDeleteOne) Where(ps ...predicate.HelpDocument) *HelpDocumentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HelpDocumentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{helpdocument.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HelpDocumentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
