// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/helpdocument"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// HelpDocumentCreate is the builder for creating a HelpDocument entity.
type HelpDocumentCreate struct {
	config
	mutation *HelpDocumentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSlug sets the "slug" field.
func (_c *HelpDocumentCreate) SetSlug(v string) *HelpDocumentCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *HelpDocumentCreate) SetTitle(v string) *HelpDocumentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *HelpDocumentCreate) SetCategory(v string) *HelpDocumentCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *HelpDocumentCreate) SetSummary(v string) *HelpDocumentCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableSummary(v *string) *HelpDocumentCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetContentMarkdown sets the "content_markdown" field.
func (_c *HelpDocumentCreate) SetContentMarkdown(v string) *HelpDocumentCreate {
	_c.mutation.SetContentMarkdown(v)
	return _c
}

// SetSelectorSchema sets the "selector_schema" field.
func (_c *HelpDocumentCreate) SetSelectorSchema(v map[string]interface{}) *HelpDocumentCreate {
	_c.mutation.SetSelectorSchema(v)
	return _c
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (_c *HelpDocumentCreate) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentCreate {
	_c.mutation.SetPublishedSnapshot(v)
	return _c
}

// SetPublicationHistory sets the "publication_history" field.
func (_c *HelpDocumentCreate) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentCreate {
	_c.mutation.SetPublicationHistory(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *HelpDocumentCreate) SetStatus(v string) *HelpDocumentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableStatus(v *string) *HelpDocumentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *HelpDocumentCreate) SetVersion(v int) *HelpDocumentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableVersion(v *int) *HelpDocumentCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *HelpDocumentCreate) SetPublishedAt(v time.Time) *HelpDocumentCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillablePublishedAt(v *time.Time) *HelpDocumentCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *HelpDocumentCreate) SetUpdatedBy(v int64) *HelpDocumentCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableUpdatedBy(v *int64) *HelpDocumentCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *HelpDocumentCreate) SetCreatedAt(v time.Time) *HelpDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableCreatedAt(v *time.Time) *HelpDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *HelpDocumentCreate) SetUpdatedAt(v time.Time) *HelpDocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *HelpDocumentCreate) SetNillableUpdatedAt(v *time.Time) *HelpDocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the HelpDocumentMutation object of the builder.
func (_c *HelpDocumentCreate) Mutation() *HelpDocumentMutation {
	return _c.mutation
}

// Save creates the HelpDocument in the database.
func (_c *HelpDocumentCreate) Save(ctx context.Context) (*HelpDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HelpDocumentCreate) SaveX(ctx context.Context) *HelpDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HelpDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HelpDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *HelpDocumentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := helpdocument.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := helpdocument.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := helpdocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := helpdocument.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HelpDocumentCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "HelpDocument.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := helpdocument.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "HelpDocument.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := helpdocument.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "HelpDocument.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := helpdocument.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := helpdocument.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentMarkdown(); !ok {
		return &ValidationError{Name: "content_markdown", err: errors.New(`ent: missing required field "HelpDocument.content_markdown"`)}
	}
	if v, ok := _c.mutation.ContentMarkdown(); ok {
		if err := helpdocument.ContentMarkdownValidator(v); err != nil {
			return &ValidationError{Name: "content_markdown", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.content_markdown": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "HelpDocument.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := helpdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "HelpDocument.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "HelpDocument.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "HelpDocument.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "HelpDocument.updated_at"`)}
	}
	return nil
}

func (_c *HelpDocumentCreate) sqlSave(ctx context.Context) (*HelpDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HelpDocumentCreate) createSpec() (*HelpDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &HelpDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(helpdocument.Table, sqlgraph.NewFieldSpec(helpdocument.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(helpdocument.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(helpdocument.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(helpdocument.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(helpdocument.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.ContentMarkdown(); ok {
		_spec.SetField(helpdocument.FieldContentMarkdown, field.TypeString, value)
		_node.ContentMarkdown = value
	}
	if value, ok := _c.mutation.SelectorSchema(); ok {
		_spec.SetField(helpdocument.FieldSelectorSchema, field.TypeJSON, value)
		_node.SelectorSchema = value
	}
	if value, ok := _c.mutation.PublishedSnapshot(); ok {
		_spec.SetField(helpdocument.FieldPublishedSnapshot, field.TypeJSON, value)
		_node.PublishedSnapshot = value
	}
	if value, ok := _c.mutation.PublicationHistory(); ok {
		_spec.SetField(helpdocument.FieldPublicationHistory, field.TypeJSON, value)
		_node.PublicationHistory = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(helpdocument.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(helpdocument.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(helpdocument.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(helpdocument.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(helpdocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(helpdocument.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HelpDocument.Create().
//		SetSlug(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HelpDocumentUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *HelpDocumentCreate) OnConflict(opts ...sql.ConflictOption) *HelpDocumentUpsertOne {
	_c.conflict = opts
	return &HelpDocumentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HelpDocumentCreate) OnConflictColumns(columns ...string) *HelpDocumentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HelpDocumentUpsertOne{
		create: _c,
	}
}

type (
	// HelpDocumentUpsertOne is the builder for "upsert"-ing
	//  one HelpDocument node.
	HelpDocumentUpsertOne struct {
		create *HelpDocumentCreate
	}

	// HelpDocumentUpsert is the "OnConflict" setter.
	HelpDocumentUpsert struct {
		*sql.UpdateSet
	}
)

// SetSlug sets the "slug" field.
func (u *HelpDocumentUpsert) SetSlug(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateSlug() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldSlug)
	return u
}

// SetTitle sets the "title" field.
func (u *HelpDocumentUpsert) SetTitle(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateTitle() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldTitle)
	return u
}

// SetCategory sets the "category" field.
func (u *HelpDocumentUpsert) SetCategory(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateCategory() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldCategory)
	return u
}

// SetSummary sets the "summary" field.
func (u *HelpDocumentUpsert) SetSummary(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateSummary() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *HelpDocumentUpsert) ClearSummary() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldSummary)
	return u
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *HelpDocumentUpsert) SetContentMarkdown(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldContentMarkdown, v)
	return u
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateContentMarkdown() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldContentMarkdown)
	return u
}

// SetSelectorSchema sets the "selector_schema" field.
func (u *HelpDocumentUpsert) SetSelectorSchema(v map[string]interface{}) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldSelectorSchema, v)
	return u
}

// UpdateSelectorSchema sets the "selector_schema" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateSelectorSchema() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldSelectorSchema)
	return u
}

// ClearSelectorSchema clears the value of the "selector_schema" field.
func (u *HelpDocumentUpsert) ClearSelectorSchema() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldSelectorSchema)
	return u
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *HelpDocumentUpsert) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldPublishedSnapshot, v)
	return u
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdatePublishedSnapshot() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldPublishedSnapshot)
	return u
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *HelpDocumentUpsert) ClearPublishedSnapshot() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldPublishedSnapshot)
	return u
}

// SetPublicationHistory sets the "publication_history" field.
func (u *HelpDocumentUpsert) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldPublicationHistory, v)
	return u
}

// UpdatePublicationHistory sets the "publication_history" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdatePublicationHistory() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldPublicationHistory)
	return u
}

// ClearPublicationHistory clears the value of the "publication_history" field.
func (u *HelpDocumentUpsert) ClearPublicationHistory() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldPublicationHistory)
	return u
}

// SetStatus sets the "status" field.
func (u *HelpDocumentUpsert) SetStatus(v string) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateStatus() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldStatus)
	return u
}

// SetVersion sets the "version" field.
func (u *HelpDocumentUpsert) SetVersion(v int) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateVersion() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *HelpDocumentUpsert) AddVersion(v int) *HelpDocumentUpsert {
	u.Add(helpdocument.FieldVersion, v)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *HelpDocumentUpsert) SetPublishedAt(v time.Time) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdatePublishedAt() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HelpDocumentUpsert) ClearPublishedAt() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldPublishedAt)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HelpDocumentUpsert) SetUpdatedBy(v int64) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateUpdatedBy() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *HelpDocumentUpsert) AddUpdatedBy(v int64) *HelpDocumentUpsert {
	u.Add(helpdocument.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HelpDocumentUpsert) ClearUpdatedBy() *HelpDocumentUpsert {
	u.SetNull(helpdocument.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HelpDocumentUpsert) SetUpdatedAt(v time.Time) *HelpDocumentUpsert {
	u.Set(helpdocument.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HelpDocumentUpsert) UpdateUpdatedAt() *HelpDocumentUpsert {
	u.SetExcluded(helpdocument.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HelpDocumentUpsertOne) UpdateNewValues() *HelpDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(helpdocument.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *HelpDocumentUpsertOne) Ignore() *HelpDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HelpDocumentUpsertOne) DoNothing() *HelpDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HelpDocumentCreate.OnConflict
// documentation for more info.
func (u *HelpDocumentUpsertOne) Update(set func(*HelpDocumentUpsert)) *HelpDocumentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HelpDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *HelpDocumentUpsertOne) SetSlug(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateSlug() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *HelpDocumentUpsertOne) SetTitle(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateTitle() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateTitle()
	})
}

// SetCategory sets the "category" field.
func (u *HelpDocumentUpsertOne) SetCategory(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateCategory() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateCategory()
	})
}

// SetSummary sets the "summary" field.
func (u *HelpDocumentUpsertOne) SetSummary(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateSummary() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *HelpDocumentUpsertOne) ClearSummary() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearSummary()
	})
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *HelpDocumentUpsertOne) SetContentMarkdown(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetContentMarkdown(v)
	})
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateContentMarkdown() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateContentMarkdown()
	})
}

// SetSelectorSchema sets the "selector_schema" field.
func (u *HelpDocumentUpsertOne) SetSelectorSchema(v map[string]interface{}) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSelectorSchema(v)
	})
}

// UpdateSelectorSchema sets the "selector_schema" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateSelectorSchema() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSelectorSchema()
	})
}

// ClearSelectorSchema clears the value of the "selector_schema" field.
func (u *HelpDocumentUpsertOne) ClearSelectorSchema() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearSelectorSchema()
	})
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *HelpDocumentUpsertOne) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublishedSnapshot(v)
	})
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdatePublishedSnapshot() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublishedSnapshot()
	})
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *HelpDocumentUpsertOne) ClearPublishedSnapshot() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublishedSnapshot()
	})
}

// SetPublicationHistory sets the "publication_history" field.
func (u *HelpDocumentUpsertOne) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublicationHistory(v)
	})
}

// UpdatePublicationHistory sets the "publication_history" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdatePublicationHistory() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublicationHistory()
	})
}

// ClearPublicationHistory clears the value of the "publication_history" field.
func (u *HelpDocumentUpsertOne) ClearPublicationHistory() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublicationHistory()
	})
}

// SetStatus sets the "status" field.
func (u *HelpDocumentUpsertOne) SetStatus(v string) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateStatus() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *HelpDocumentUpsertOne) SetVersion(v int) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *HelpDocumentUpsertOne) AddVersion(v int) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateVersion() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateVersion()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *HelpDocumentUpsertOne) SetPublishedAt(v time.Time) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdatePublishedAt() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HelpDocumentUpsertOne) ClearPublishedAt() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HelpDocumentUpsertOne) SetUpdatedBy(v int64) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *HelpDocumentUpsertOne) AddUpdatedBy(v int64) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateUpdatedBy() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HelpDocumentUpsertOne) ClearUpdatedBy() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HelpDocumentUpsertOne) SetUpdatedAt(v time.Time) *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HelpDocumentUpsertOne) UpdateUpdatedAt() *HelpDocumentUpsertOne {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *HelpDocumentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HelpDocumentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HelpDocumentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *HelpDocumentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *HelpDocumentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// HelpDocumentCreateBulk is the builder for creating many HelpDocument entities in bulk.
type HelpDocumentCreateBulk struct {
	config
	err      error
	builders []*HelpDocumentCreate
	conflict []sql.ConflictOption
}

// Save creates the HelpDocument entities in the database.
func (_c *HelpDocumentCreateBulk) Save(ctx context.Context) ([]*HelpDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HelpDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HelpDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HelpDocumentCreateBulk) SaveX(ctx context.Context) []*HelpDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HelpDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HelpDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.HelpDocument.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.HelpDocumentUpsert) {
//			SetSlug(v+v).
//		}).
//		Exec(ctx)
func (_c *HelpDocumentCreateBulk) OnConflict(opts ...sql.ConflictOption) *HelpDocumentUpsertBulk {
	_c.conflict = opts
	return &HelpDocumentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *HelpDocumentCreateBulk) OnConflictColumns(columns ...string) *HelpDocumentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &HelpDocumentUpsertBulk{
		create: _c,
	}
}

// HelpDocumentUpsertBulk is the builder for "upsert"-ing
// a bulk of HelpDocument nodes.
type HelpDocumentUpsertBulk struct {
	create *HelpDocumentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *HelpDocumentUpsertBulk) UpdateNewValues() *HelpDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(helpdocument.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.HelpDocument.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *HelpDocumentUpsertBulk) Ignore() *HelpDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *HelpDocumentUpsertBulk) DoNothing() *HelpDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the HelpDocumentCreateBulk.OnConflict
// documentation for more info.
func (u *HelpDocumentUpsertBulk) Update(set func(*HelpDocumentUpsert)) *HelpDocumentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&HelpDocumentUpsert{UpdateSet: update})
	}))
	return u
}

// SetSlug sets the "slug" field.
func (u *HelpDocumentUpsertBulk) SetSlug(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateSlug() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSlug()
	})
}

// SetTitle sets the "title" field.
func (u *HelpDocumentUpsertBulk) SetTitle(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateTitle() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateTitle()
	})
}

// SetCategory sets the "category" field.
func (u *HelpDocumentUpsertBulk) SetCategory(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateCategory() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateCategory()
	})
}

// SetSummary sets the "summary" field.
func (u *HelpDocumentUpsertBulk) SetSummary(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateSummary() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *HelpDocumentUpsertBulk) ClearSummary() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearSummary()
	})
}

// SetContentMarkdown sets the "content_markdown" field.
func (u *HelpDocumentUpsertBulk) SetContentMarkdown(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetContentMarkdown(v)
	})
}

// UpdateContentMarkdown sets the "content_markdown" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateContentMarkdown() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateContentMarkdown()
	})
}

// SetSelectorSchema sets the "selector_schema" field.
func (u *HelpDocumentUpsertBulk) SetSelectorSchema(v map[string]interface{}) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetSelectorSchema(v)
	})
}

// UpdateSelectorSchema sets the "selector_schema" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateSelectorSchema() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateSelectorSchema()
	})
}

// ClearSelectorSchema clears the value of the "selector_schema" field.
func (u *HelpDocumentUpsertBulk) ClearSelectorSchema() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearSelectorSchema()
	})
}

// SetPublishedSnapshot sets the "published_snapshot" field.
func (u *HelpDocumentUpsertBulk) SetPublishedSnapshot(v *domain.HelpDocumentSnapshot) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublishedSnapshot(v)
	})
}

// UpdatePublishedSnapshot sets the "published_snapshot" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdatePublishedSnapshot() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublishedSnapshot()
	})
}

// ClearPublishedSnapshot clears the value of the "published_snapshot" field.
func (u *HelpDocumentUpsertBulk) ClearPublishedSnapshot() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublishedSnapshot()
	})
}

// SetPublicationHistory sets the "publication_history" field.
func (u *HelpDocumentUpsertBulk) SetPublicationHistory(v []domain.HelpDocumentSnapshot) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublicationHistory(v)
	})
}

// UpdatePublicationHistory sets the "publication_history" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdatePublicationHistory() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublicationHistory()
	})
}

// ClearPublicationHistory clears the value of the "publication_history" field.
func (u *HelpDocumentUpsertBulk) ClearPublicationHistory() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublicationHistory()
	})
}

// SetStatus sets the "status" field.
func (u *HelpDocumentUpsertBulk) SetStatus(v string) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateStatus() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateStatus()
	})
}

// SetVersion sets the "version" field.
func (u *HelpDocumentUpsertBulk) SetVersion(v int) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *HelpDocumentUpsertBulk) AddVersion(v int) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateVersion() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateVersion()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *HelpDocumentUpsertBulk) SetPublishedAt(v time.Time) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdatePublishedAt() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *HelpDocumentUpsertBulk) ClearPublishedAt() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearPublishedAt()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *HelpDocumentUpsertBulk) SetUpdatedBy(v int64) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *HelpDocumentUpsertBulk) AddUpdatedBy(v int64) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateUpdatedBy() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *HelpDocumentUpsertBulk) ClearUpdatedBy() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *HelpDocumentUpsertBulk) SetUpdatedAt(v time.Time) *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *HelpDocumentUpsertBulk) UpdateUpdatedAt() *HelpDocumentUpsertBulk {
	return u.Update(func(s *HelpDocumentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *HelpDocumentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the HelpDocumentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for HelpDocumentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *HelpDocumentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
