// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
)

// InvoiceApplicationCreate is the builder for creating a InvoiceApplication entity.
type InvoiceApplicationCreate struct {
	config
	mutation *InvoiceApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *InvoiceApplicationCreate) SetUserID(v int64) *InvoiceApplicationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrderIds sets the "order_ids" field.
func (_c *InvoiceApplicationCreate) SetOrderIds(v []int64) *InvoiceApplicationCreate {
	_c.mutation.SetOrderIds(v)
	return _c
}

// SetOrderNos sets the "order_nos" field.
func (_c *InvoiceApplicationCreate) SetOrderNos(v []string) *InvoiceApplicationCreate {
	_c.mutation.SetOrderNos(v)
	return _c
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (_c *InvoiceApplicationCreate) SetNeedPayTax(v bool) *InvoiceApplicationCreate {
	_c.mutation.SetNeedPayTax(v)
	return _c
}

// SetNillableNeedPayTax sets the "need_pay_tax" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableNeedPayTax(v *bool) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetNeedPayTax(*v)
	}
	return _c
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (_c *InvoiceApplicationCreate) SetTaxOrderNos(v []string) *InvoiceApplicationCreate {
	_c.mutation.SetTaxOrderNos(v)
	return _c
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (_c *InvoiceApplicationCreate) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationCreate {
	_c.mutation.SetValidationSnapshot(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *InvoiceApplicationCreate) SetExternalID(v string) *InvoiceApplicationCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableExternalID(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceApplicationCreate) SetStatus(v string) *InvoiceApplicationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableStatus(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *InvoiceApplicationCreate) SetTitle(v string) *InvoiceApplicationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableTitle(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *InvoiceApplicationCreate) SetRecipientEmail(v string) *InvoiceApplicationCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRecipientEmail(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRecipientEmail(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *InvoiceApplicationCreate) SetTotalAmount(v string) *InvoiceApplicationCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableTotalAmount(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetTotalAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceApplicationCreate) SetCurrency(v string) *InvoiceApplicationCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCurrency(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (_c *InvoiceApplicationCreate) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationCreate {
	_c.mutation.SetExternalSnapshot(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *InvoiceApplicationCreate) SetRequestID(v string) *InvoiceApplicationCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableRequestID(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *InvoiceApplicationCreate) SetErrorCode(v string) *InvoiceApplicationCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableErrorCode(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *InvoiceApplicationCreate) SetErrorMessage(v string) *InvoiceApplicationCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableErrorMessage(v *string) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceApplicationCreate) SetCreatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableCreatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceApplicationCreate) SetUpdatedAt(v time.Time) *InvoiceApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceApplicationCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_c *InvoiceApplicationCreate) Mutation() *InvoiceApplicationMutation {
	return _c.mutation
}

// Save creates the InvoiceApplication in the database.
func (_c *InvoiceApplicationCreate) Save(ctx context.Context) (*InvoiceApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceApplicationCreate) SaveX(ctx context.Context) *InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceApplicationCreate) defaults() {
	if _, ok := _c.mutation.OrderIds(); !ok {
		v := invoiceapplication.DefaultOrderIds()
		_c.mutation.SetOrderIds(v)
	}
	if _, ok := _c.mutation.OrderNos(); !ok {
		v := invoiceapplication.DefaultOrderNos()
		_c.mutation.SetOrderNos(v)
	}
	if _, ok := _c.mutation.NeedPayTax(); !ok {
		v := invoiceapplication.DefaultNeedPayTax
		_c.mutation.SetNeedPayTax(v)
	}
	if _, ok := _c.mutation.TaxOrderNos(); !ok {
		v := invoiceapplication.DefaultTaxOrderNos()
		_c.mutation.SetTaxOrderNos(v)
	}
	if _, ok := _c.mutation.ValidationSnapshot(); !ok {
		v := invoiceapplication.DefaultValidationSnapshot()
		_c.mutation.SetValidationSnapshot(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoiceapplication.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		v := invoiceapplication.DefaultTotalAmount
		_c.mutation.SetTotalAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := invoiceapplication.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.ExternalSnapshot(); !ok {
		v := invoiceapplication.DefaultExternalSnapshot()
		_c.mutation.SetExternalSnapshot(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invoiceapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceApplicationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InvoiceApplication.user_id"`)}
	}
	if _, ok := _c.mutation.OrderIds(); !ok {
		return &ValidationError{Name: "order_ids", err: errors.New(`ent: missing required field "InvoiceApplication.order_ids"`)}
	}
	if _, ok := _c.mutation.OrderNos(); !ok {
		return &ValidationError{Name: "order_nos", err: errors.New(`ent: missing required field "InvoiceApplication.order_nos"`)}
	}
	if _, ok := _c.mutation.NeedPayTax(); !ok {
		return &ValidationError{Name: "need_pay_tax", err: errors.New(`ent: missing required field "InvoiceApplication.need_pay_tax"`)}
	}
	if _, ok := _c.mutation.TaxOrderNos(); !ok {
		return &ValidationError{Name: "tax_order_nos", err: errors.New(`ent: missing required field "InvoiceApplication.tax_order_nos"`)}
	}
	if _, ok := _c.mutation.ValidationSnapshot(); !ok {
		return &ValidationError{Name: "validation_snapshot", err: errors.New(`ent: missing required field "InvoiceApplication.validation_snapshot"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := invoiceapplication.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.external_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "InvoiceApplication.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := invoiceapplication.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := invoiceapplication.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.recipient_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "InvoiceApplication.total_amount"`)}
	}
	if v, ok := _c.mutation.TotalAmount(); ok {
		if err := invoiceapplication.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.total_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "InvoiceApplication.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoiceapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalSnapshot(); !ok {
		return &ValidationError{Name: "external_snapshot", err: errors.New(`ent: missing required field "InvoiceApplication.external_snapshot"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := invoiceapplication.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := invoiceapplication.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InvoiceApplication.updated_at"`)}
	}
	return nil
}

func (_c *InvoiceApplicationCreate) sqlSave(ctx context.Context) (*InvoiceApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceApplicationCreate) createSpec() (*InvoiceApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoiceapplication.Table, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(invoiceapplication.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.OrderIds(); ok {
		_spec.SetField(invoiceapplication.FieldOrderIds, field.TypeJSON, value)
		_node.OrderIds = value
	}
	if value, ok := _c.mutation.OrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldOrderNos, field.TypeJSON, value)
		_node.OrderNos = value
	}
	if value, ok := _c.mutation.NeedPayTax(); ok {
		_spec.SetField(invoiceapplication.FieldNeedPayTax, field.TypeBool, value)
		_node.NeedPayTax = value
	}
	if value, ok := _c.mutation.TaxOrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldTaxOrderNos, field.TypeJSON, value)
		_node.TaxOrderNos = value
	}
	if value, ok := _c.mutation.ValidationSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldValidationSnapshot, field.TypeJSON, value)
		_node.ValidationSnapshot = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(invoiceapplication.FieldExternalID, field.TypeString, value)
		_node.ExternalID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(invoiceapplication.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(invoiceapplication.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = &value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeString, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoiceapplication.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ExternalSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldExternalSnapshot, field.TypeJSON, value)
		_node.ExternalSnapshot = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(invoiceapplication.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertOne {
	_c.conflict = opts
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreate) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceApplicationUpsertOne is the builder for "upsert"-ing
	//  one InvoiceApplication node.
	InvoiceApplicationUpsertOne struct {
		create *InvoiceApplicationCreate
	}

	// InvoiceApplicationUpsert is the "OnConflict" setter.
	InvoiceApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsert) SetUserID(v int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUserID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceApplicationUpsert) AddUserID(v int64) *InvoiceApplicationUpsert {
	u.Add(invoiceapplication.FieldUserID, v)
	return u
}

// SetOrderIds sets the "order_ids" field.
func (u *InvoiceApplicationUpsert) SetOrderIds(v []int64) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldOrderIds, v)
	return u
}

// UpdateOrderIds sets the "order_ids" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateOrderIds() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldOrderIds)
	return u
}

// SetOrderNos sets the "order_nos" field.
func (u *InvoiceApplicationUpsert) SetOrderNos(v []string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldOrderNos, v)
	return u
}

// UpdateOrderNos sets the "order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateOrderNos() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldOrderNos)
	return u
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (u *InvoiceApplicationUpsert) SetNeedPayTax(v bool) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldNeedPayTax, v)
	return u
}

// UpdateNeedPayTax sets the "need_pay_tax" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateNeedPayTax() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldNeedPayTax)
	return u
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (u *InvoiceApplicationUpsert) SetTaxOrderNos(v []string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTaxOrderNos, v)
	return u
}

// UpdateTaxOrderNos sets the "tax_order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTaxOrderNos() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTaxOrderNos)
	return u
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (u *InvoiceApplicationUpsert) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldValidationSnapshot, v)
	return u
}

// UpdateValidationSnapshot sets the "validation_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateValidationSnapshot() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldValidationSnapshot)
	return u
}

// SetExternalID sets the "external_id" field.
func (u *InvoiceApplicationUpsert) SetExternalID(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldExternalID, v)
	return u
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateExternalID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldExternalID)
	return u
}

// ClearExternalID clears the value of the "external_id" field.
func (u *InvoiceApplicationUpsert) ClearExternalID() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldExternalID)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsert) SetStatus(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateStatus() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldStatus)
	return u
}

// SetTitle sets the "title" field.
func (u *InvoiceApplicationUpsert) SetTitle(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTitle() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *InvoiceApplicationUpsert) ClearTitle() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldTitle)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceApplicationUpsert) SetRecipientEmail(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRecipientEmail() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRecipientEmail)
	return u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceApplicationUpsert) ClearRecipientEmail() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRecipientEmail)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsert) SetTotalAmount(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateTotalAmount() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldTotalAmount)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceApplicationUpsert) SetCurrency(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateCurrency() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldCurrency)
	return u
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (u *InvoiceApplicationUpsert) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldExternalSnapshot, v)
	return u
}

// UpdateExternalSnapshot sets the "external_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateExternalSnapshot() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldExternalSnapshot)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *InvoiceApplicationUpsert) SetRequestID(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateRequestID() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *InvoiceApplicationUpsert) ClearRequestID() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldRequestID)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *InvoiceApplicationUpsert) SetErrorCode(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateErrorCode() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *InvoiceApplicationUpsert) ClearErrorCode() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceApplicationUpsert) SetErrorMessage(v string) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateErrorMessage() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceApplicationUpsert) ClearErrorMessage() *InvoiceApplicationUpsert {
	u.SetNull(invoiceapplication.FieldErrorMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsert) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsert {
	u.Set(invoiceapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsert) UpdateUpdatedAt() *InvoiceApplicationUpsert {
	u.SetExcluded(invoiceapplication.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertOne) UpdateNewValues() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoiceapplication.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceApplicationUpsertOne) Ignore() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertOne) DoNothing() *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreate.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertOne) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertOne) SetUserID(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceApplicationUpsertOne) AddUserID(v int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUserID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderIds sets the "order_ids" field.
func (u *InvoiceApplicationUpsertOne) SetOrderIds(v []int64) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOrderIds(v)
	})
}

// UpdateOrderIds sets the "order_ids" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateOrderIds() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOrderIds()
	})
}

// SetOrderNos sets the "order_nos" field.
func (u *InvoiceApplicationUpsertOne) SetOrderNos(v []string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOrderNos(v)
	})
}

// UpdateOrderNos sets the "order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateOrderNos() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOrderNos()
	})
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (u *InvoiceApplicationUpsertOne) SetNeedPayTax(v bool) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetNeedPayTax(v)
	})
}

// UpdateNeedPayTax sets the "need_pay_tax" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateNeedPayTax() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateNeedPayTax()
	})
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (u *InvoiceApplicationUpsertOne) SetTaxOrderNos(v []string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxOrderNos(v)
	})
}

// UpdateTaxOrderNos sets the "tax_order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTaxOrderNos() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxOrderNos()
	})
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (u *InvoiceApplicationUpsertOne) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetValidationSnapshot(v)
	})
}

// UpdateValidationSnapshot sets the "validation_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateValidationSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateValidationSnapshot()
	})
}

// SetExternalID sets the "external_id" field.
func (u *InvoiceApplicationUpsertOne) SetExternalID(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateExternalID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *InvoiceApplicationUpsertOne) ClearExternalID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearExternalID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertOne) SetStatus(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateStatus() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceApplicationUpsertOne) SetTitle(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTitle() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *InvoiceApplicationUpsertOne) ClearTitle() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearTitle()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceApplicationUpsertOne) SetRecipientEmail(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRecipientEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRecipientEmail()
	})
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceApplicationUpsertOne) ClearRecipientEmail() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRecipientEmail()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertOne) SetTotalAmount(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateTotalAmount() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceApplicationUpsertOne) SetCurrency(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateCurrency() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCurrency()
	})
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (u *InvoiceApplicationUpsertOne) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetExternalSnapshot(v)
	})
}

// UpdateExternalSnapshot sets the "external_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateExternalSnapshot() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateExternalSnapshot()
	})
}

// SetRequestID sets the "request_id" field.
func (u *InvoiceApplicationUpsertOne) SetRequestID(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateRequestID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *InvoiceApplicationUpsertOne) ClearRequestID() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRequestID()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *InvoiceApplicationUpsertOne) SetErrorCode(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateErrorCode() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *InvoiceApplicationUpsertOne) ClearErrorCode() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceApplicationUpsertOne) SetErrorMessage(v string) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateErrorMessage() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceApplicationUpsertOne) ClearErrorMessage() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertOne) UpdateUpdatedAt() *InvoiceApplicationUpsertOne {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceApplicationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceApplicationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvoiceApplicationCreateBulk is the builder for creating many InvoiceApplication entities in bulk.
type InvoiceApplicationCreateBulk struct {
	config
	err      error
	builders []*InvoiceApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the InvoiceApplication entities in the database.
func (_c *InvoiceApplicationCreateBulk) Save(ctx context.Context) ([]*InvoiceApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvoiceApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) SaveX(ctx context.Context) []*InvoiceApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InvoiceApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceApplicationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceApplicationUpsertBulk {
	_c.conflict = opts
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceApplicationCreateBulk) OnConflictColumns(columns ...string) *InvoiceApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceApplicationUpsertBulk{
		create: _c,
	}
}

// InvoiceApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of InvoiceApplication nodes.
type InvoiceApplicationUpsertBulk struct {
	create *InvoiceApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) UpdateNewValues() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoiceapplication.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InvoiceApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceApplicationUpsertBulk) Ignore() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceApplicationUpsertBulk) DoNothing() *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceApplicationUpsertBulk) Update(set func(*InvoiceApplicationUpsert)) *InvoiceApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InvoiceApplicationUpsertBulk) SetUserID(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InvoiceApplicationUpsertBulk) AddUserID(v int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUserID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderIds sets the "order_ids" field.
func (u *InvoiceApplicationUpsertBulk) SetOrderIds(v []int64) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOrderIds(v)
	})
}

// UpdateOrderIds sets the "order_ids" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateOrderIds() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOrderIds()
	})
}

// SetOrderNos sets the "order_nos" field.
func (u *InvoiceApplicationUpsertBulk) SetOrderNos(v []string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetOrderNos(v)
	})
}

// UpdateOrderNos sets the "order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateOrderNos() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateOrderNos()
	})
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (u *InvoiceApplicationUpsertBulk) SetNeedPayTax(v bool) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetNeedPayTax(v)
	})
}

// UpdateNeedPayTax sets the "need_pay_tax" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateNeedPayTax() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateNeedPayTax()
	})
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (u *InvoiceApplicationUpsertBulk) SetTaxOrderNos(v []string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTaxOrderNos(v)
	})
}

// UpdateTaxOrderNos sets the "tax_order_nos" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTaxOrderNos() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTaxOrderNos()
	})
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetValidationSnapshot(v)
	})
}

// UpdateValidationSnapshot sets the "validation_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateValidationSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateValidationSnapshot()
	})
}

// SetExternalID sets the "external_id" field.
func (u *InvoiceApplicationUpsertBulk) SetExternalID(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetExternalID(v)
	})
}

// UpdateExternalID sets the "external_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateExternalID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateExternalID()
	})
}

// ClearExternalID clears the value of the "external_id" field.
func (u *InvoiceApplicationUpsertBulk) ClearExternalID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearExternalID()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceApplicationUpsertBulk) SetStatus(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateStatus() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateStatus()
	})
}

// SetTitle sets the "title" field.
func (u *InvoiceApplicationUpsertBulk) SetTitle(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTitle() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *InvoiceApplicationUpsertBulk) ClearTitle() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearTitle()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *InvoiceApplicationUpsertBulk) SetRecipientEmail(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRecipientEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRecipientEmail()
	})
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (u *InvoiceApplicationUpsertBulk) ClearRecipientEmail() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRecipientEmail()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *InvoiceApplicationUpsertBulk) SetTotalAmount(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateTotalAmount() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceApplicationUpsertBulk) SetCurrency(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateCurrency() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateCurrency()
	})
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (u *InvoiceApplicationUpsertBulk) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetExternalSnapshot(v)
	})
}

// UpdateExternalSnapshot sets the "external_snapshot" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateExternalSnapshot() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateExternalSnapshot()
	})
}

// SetRequestID sets the "request_id" field.
func (u *InvoiceApplicationUpsertBulk) SetRequestID(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateRequestID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *InvoiceApplicationUpsertBulk) ClearRequestID() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearRequestID()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *InvoiceApplicationUpsertBulk) SetErrorCode(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateErrorCode() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *InvoiceApplicationUpsertBulk) ClearErrorCode() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *InvoiceApplicationUpsertBulk) SetErrorMessage(v string) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateErrorMessage() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *InvoiceApplicationUpsertBulk) ClearErrorMessage() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.ClearErrorMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceApplicationUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceApplicationUpsertBulk) UpdateUpdatedAt() *InvoiceApplicationUpsertBulk {
	return u.Update(func(s *InvoiceApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InvoiceApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InvoiceApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InvoiceApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
