// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// InvoiceApplicationUpdate is the builder for updating InvoiceApplication entities.
type InvoiceApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdate) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdate) SetUserID(v int64) *InvoiceApplicationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableUserID(v *int64) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceApplicationUpdate) AddUserID(v int64) *InvoiceApplicationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderIds sets the "order_ids" field.
func (_u *InvoiceApplicationUpdate) SetOrderIds(v []int64) *InvoiceApplicationUpdate {
	_u.mutation.SetOrderIds(v)
	return _u
}

// AppendOrderIds appends value to the "order_ids" field.
func (_u *InvoiceApplicationUpdate) AppendOrderIds(v []int64) *InvoiceApplicationUpdate {
	_u.mutation.AppendOrderIds(v)
	return _u
}

// SetOrderNos sets the "order_nos" field.
func (_u *InvoiceApplicationUpdate) SetOrderNos(v []string) *InvoiceApplicationUpdate {
	_u.mutation.SetOrderNos(v)
	return _u
}

// AppendOrderNos appends value to the "order_nos" field.
func (_u *InvoiceApplicationUpdate) AppendOrderNos(v []string) *InvoiceApplicationUpdate {
	_u.mutation.AppendOrderNos(v)
	return _u
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (_u *InvoiceApplicationUpdate) SetNeedPayTax(v bool) *InvoiceApplicationUpdate {
	_u.mutation.SetNeedPayTax(v)
	return _u
}

// SetNillableNeedPayTax sets the "need_pay_tax" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableNeedPayTax(v *bool) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetNeedPayTax(*v)
	}
	return _u
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (_u *InvoiceApplicationUpdate) SetTaxOrderNos(v []string) *InvoiceApplicationUpdate {
	_u.mutation.SetTaxOrderNos(v)
	return _u
}

// AppendTaxOrderNos appends value to the "tax_order_nos" field.
func (_u *InvoiceApplicationUpdate) AppendTaxOrderNos(v []string) *InvoiceApplicationUpdate {
	_u.mutation.AppendTaxOrderNos(v)
	return _u
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (_u *InvoiceApplicationUpdate) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationUpdate {
	_u.mutation.SetValidationSnapshot(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *InvoiceApplicationUpdate) SetExternalID(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableExternalID(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *InvoiceApplicationUpdate) ClearExternalID() *InvoiceApplicationUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdate) SetStatus(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableStatus(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceApplicationUpdate) SetTitle(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTitle(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *InvoiceApplicationUpdate) ClearTitle() *InvoiceApplicationUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceApplicationUpdate) SetRecipientEmail(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRecipientEmail(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (_u *InvoiceApplicationUpdate) ClearRecipientEmail() *InvoiceApplicationUpdate {
	_u.mutation.ClearRecipientEmail()
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdate) SetTotalAmount(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableTotalAmount(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceApplicationUpdate) SetCurrency(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableCurrency(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (_u *InvoiceApplicationUpdate) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationUpdate {
	_u.mutation.SetExternalSnapshot(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *InvoiceApplicationUpdate) SetRequestID(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableRequestID(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *InvoiceApplicationUpdate) ClearRequestID() *InvoiceApplicationUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *InvoiceApplicationUpdate) SetErrorCode(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableErrorCode(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *InvoiceApplicationUpdate) ClearErrorCode() *InvoiceApplicationUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *InvoiceApplicationUpdate) SetErrorMessage(v string) *InvoiceApplicationUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *InvoiceApplicationUpdate) SetNillableErrorMessage(v *string) *InvoiceApplicationUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *InvoiceApplicationUpdate) ClearErrorMessage() *InvoiceApplicationUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdate) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdate) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdate) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := invoiceapplication.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceapplication.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoiceapplication.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalAmount(); ok {
		if err := invoiceapplication.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.total_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoiceapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := invoiceapplication.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := invoiceapplication.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoiceapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoiceapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderIds(); ok {
		_spec.SetField(invoiceapplication.FieldOrderIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOrderIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldOrderIds, value)
		})
	}
	if value, ok := _u.mutation.OrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldOrderNos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOrderNos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldOrderNos, value)
		})
	}
	if value, ok := _u.mutation.NeedPayTax(); ok {
		_spec.SetField(invoiceapplication.FieldNeedPayTax, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TaxOrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldTaxOrderNos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTaxOrderNos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldTaxOrderNos, value)
		})
	}
	if value, ok := _u.mutation.ValidationSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldValidationSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(invoiceapplication.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(invoiceapplication.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceapplication.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(invoiceapplication.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoiceapplication.FieldRecipientEmail, field.TypeString, value)
	}
	if _u.mutation.RecipientEmailCleared() {
		_spec.ClearField(invoiceapplication.FieldRecipientEmail, field.TypeString)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoiceapplication.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldExternalSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(invoiceapplication.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(invoiceapplication.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(invoiceapplication.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(invoiceapplication.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceApplicationUpdateOne is the builder for updating a single InvoiceApplication entity.
type InvoiceApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceApplicationMutation
}

// SetUserID sets the "user_id" field.
func (_u *InvoiceApplicationUpdateOne) SetUserID(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableUserID(v *int64) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *InvoiceApplicationUpdateOne) AddUserID(v int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderIds sets the "order_ids" field.
func (_u *InvoiceApplicationUpdateOne) SetOrderIds(v []int64) *InvoiceApplicationUpdateOne {
	_u.mutation.SetOrderIds(v)
	return _u
}

// AppendOrderIds appends value to the "order_ids" field.
func (_u *InvoiceApplicationUpdateOne) AppendOrderIds(v []int64) *InvoiceApplicationUpdateOne {
	_u.mutation.AppendOrderIds(v)
	return _u
}

// SetOrderNos sets the "order_nos" field.
func (_u *InvoiceApplicationUpdateOne) SetOrderNos(v []string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetOrderNos(v)
	return _u
}

// AppendOrderNos appends value to the "order_nos" field.
func (_u *InvoiceApplicationUpdateOne) AppendOrderNos(v []string) *InvoiceApplicationUpdateOne {
	_u.mutation.AppendOrderNos(v)
	return _u
}

// SetNeedPayTax sets the "need_pay_tax" field.
func (_u *InvoiceApplicationUpdateOne) SetNeedPayTax(v bool) *InvoiceApplicationUpdateOne {
	_u.mutation.SetNeedPayTax(v)
	return _u
}

// SetNillableNeedPayTax sets the "need_pay_tax" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableNeedPayTax(v *bool) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetNeedPayTax(*v)
	}
	return _u
}

// SetTaxOrderNos sets the "tax_order_nos" field.
func (_u *InvoiceApplicationUpdateOne) SetTaxOrderNos(v []string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTaxOrderNos(v)
	return _u
}

// AppendTaxOrderNos appends value to the "tax_order_nos" field.
func (_u *InvoiceApplicationUpdateOne) AppendTaxOrderNos(v []string) *InvoiceApplicationUpdateOne {
	_u.mutation.AppendTaxOrderNos(v)
	return _u
}

// SetValidationSnapshot sets the "validation_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) SetValidationSnapshot(v map[string]interface{}) *InvoiceApplicationUpdateOne {
	_u.mutation.SetValidationSnapshot(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *InvoiceApplicationUpdateOne) SetExternalID(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableExternalID(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *InvoiceApplicationUpdateOne) ClearExternalID() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceApplicationUpdateOne) SetStatus(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableStatus(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InvoiceApplicationUpdateOne) SetTitle(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTitle(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *InvoiceApplicationUpdateOne) ClearTitle() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *InvoiceApplicationUpdateOne) SetRecipientEmail(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRecipientEmail(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// ClearRecipientEmail clears the value of the "recipient_email" field.
func (_u *InvoiceApplicationUpdateOne) ClearRecipientEmail() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRecipientEmail()
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *InvoiceApplicationUpdateOne) SetTotalAmount(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableTotalAmount(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceApplicationUpdateOne) SetCurrency(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableCurrency(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetExternalSnapshot sets the "external_snapshot" field.
func (_u *InvoiceApplicationUpdateOne) SetExternalSnapshot(v map[string]interface{}) *InvoiceApplicationUpdateOne {
	_u.mutation.SetExternalSnapshot(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *InvoiceApplicationUpdateOne) SetRequestID(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableRequestID(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *InvoiceApplicationUpdateOne) ClearRequestID() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *InvoiceApplicationUpdateOne) SetErrorCode(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableErrorCode(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *InvoiceApplicationUpdateOne) ClearErrorCode() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *InvoiceApplicationUpdateOne) SetErrorMessage(v string) *InvoiceApplicationUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *InvoiceApplicationUpdateOne) SetNillableErrorMessage(v *string) *InvoiceApplicationUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *InvoiceApplicationUpdateOne) ClearErrorMessage() *InvoiceApplicationUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceApplicationUpdateOne) SetUpdatedAt(v time.Time) *InvoiceApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the InvoiceApplicationMutation object of the builder.
func (_u *InvoiceApplicationUpdateOne) Mutation() *InvoiceApplicationMutation {
	return _u.mutation
}

// Where appends a list predicates to the InvoiceApplicationUpdate builder.
func (_u *InvoiceApplicationUpdateOne) Where(ps ...predicate.InvoiceApplication) *InvoiceApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceApplicationUpdateOne) Select(field string, fields ...string) *InvoiceApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InvoiceApplication entity.
func (_u *InvoiceApplicationUpdateOne) Save(ctx context.Context) (*InvoiceApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) SaveX(ctx context.Context) *InvoiceApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := invoiceapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := invoiceapplication.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoiceapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := invoiceapplication.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := invoiceapplication.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalAmount(); ok {
		if err := invoiceapplication.TotalAmountValidator(v); err != nil {
			return &ValidationError{Name: "total_amount", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.total_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoiceapplication.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := invoiceapplication.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := invoiceapplication.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "InvoiceApplication.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *InvoiceApplicationUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoiceapplication.Table, invoiceapplication.Columns, sqlgraph.NewFieldSpec(invoiceapplication.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceapplication.FieldID)
		for _, f := range fields {
			if !invoiceapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(invoiceapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(invoiceapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderIds(); ok {
		_spec.SetField(invoiceapplication.FieldOrderIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOrderIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldOrderIds, value)
		})
	}
	if value, ok := _u.mutation.OrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldOrderNos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOrderNos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldOrderNos, value)
		})
	}
	if value, ok := _u.mutation.NeedPayTax(); ok {
		_spec.SetField(invoiceapplication.FieldNeedPayTax, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TaxOrderNos(); ok {
		_spec.SetField(invoiceapplication.FieldTaxOrderNos, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTaxOrderNos(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, invoiceapplication.FieldTaxOrderNos, value)
		})
	}
	if value, ok := _u.mutation.ValidationSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldValidationSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(invoiceapplication.FieldExternalID, field.TypeString, value)
	}
	if _u.mutation.ExternalIDCleared() {
		_spec.ClearField(invoiceapplication.FieldExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoiceapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(invoiceapplication.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(invoiceapplication.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(invoiceapplication.FieldRecipientEmail, field.TypeString, value)
	}
	if _u.mutation.RecipientEmailCleared() {
		_spec.ClearField(invoiceapplication.FieldRecipientEmail, field.TypeString)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(invoiceapplication.FieldTotalAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoiceapplication.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalSnapshot(); ok {
		_spec.SetField(invoiceapplication.FieldExternalSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(invoiceapplication.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(invoiceapplication.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(invoiceapplication.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(invoiceapplication.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(invoiceapplication.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(invoiceapplication.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoiceapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &InvoiceApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
