// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/invoiceapplication"
)

// InvoiceApplication is the model entity for the InvoiceApplication schema.
type InvoiceApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderIds holds the value of the "order_ids" field.
	OrderIds []int64 `json:"order_ids,omitempty"`
	// OrderNos holds the value of the "order_nos" field.
	OrderNos []string `json:"order_nos,omitempty"`
	// NeedPayTax holds the value of the "need_pay_tax" field.
	NeedPayTax bool `json:"need_pay_tax,omitempty"`
	// TaxOrderNos holds the value of the "tax_order_nos" field.
	TaxOrderNos []string `json:"tax_order_nos,omitempty"`
	// ValidationSnapshot holds the value of the "validation_snapshot" field.
	ValidationSnapshot map[string]interface{} `json:"validation_snapshot,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID *string `json:"external_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Title holds the value of the "title" field.
	Title *string `json:"title,omitempty"`
	// RecipientEmail holds the value of the "recipient_email" field.
	RecipientEmail *string `json:"recipient_email,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount string `json:"total_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// ExternalSnapshot holds the value of the "external_snapshot" field.
	ExternalSnapshot map[string]interface{} `json:"external_snapshot,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldOrderIds, invoiceapplication.FieldOrderNos, invoiceapplication.FieldTaxOrderNos, invoiceapplication.FieldValidationSnapshot, invoiceapplication.FieldExternalSnapshot:
			values[i] = new([]byte)
		case invoiceapplication.FieldNeedPayTax:
			values[i] = new(sql.NullBool)
		case invoiceapplication.FieldID, invoiceapplication.FieldUserID:
			values[i] = new(sql.NullInt64)
		case invoiceapplication.FieldExternalID, invoiceapplication.FieldStatus, invoiceapplication.FieldTitle, invoiceapplication.FieldRecipientEmail, invoiceapplication.FieldTotalAmount, invoiceapplication.FieldCurrency, invoiceapplication.FieldRequestID, invoiceapplication.FieldErrorCode, invoiceapplication.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case invoiceapplication.FieldCreatedAt, invoiceapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceApplication fields.
func (_m *InvoiceApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoiceapplication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case invoiceapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case invoiceapplication.FieldOrderIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field order_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OrderIds); err != nil {
					return fmt.Errorf("unmarshal field order_ids: %w", err)
				}
			}
		case invoiceapplication.FieldOrderNos:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field order_nos", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OrderNos); err != nil {
					return fmt.Errorf("unmarshal field order_nos: %w", err)
				}
			}
		case invoiceapplication.FieldNeedPayTax:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field need_pay_tax", values[i])
			} else if value.Valid {
				_m.NeedPayTax = value.Bool
			}
		case invoiceapplication.FieldTaxOrderNos:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tax_order_nos", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TaxOrderNos); err != nil {
					return fmt.Errorf("unmarshal field tax_order_nos: %w", err)
				}
			}
		case invoiceapplication.FieldValidationSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field validation_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ValidationSnapshot); err != nil {
					return fmt.Errorf("unmarshal field validation_snapshot: %w", err)
				}
			}
		case invoiceapplication.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = new(string)
				*_m.ExternalID = value.String
			}
		case invoiceapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case invoiceapplication.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = new(string)
				*_m.Title = value.String
			}
		case invoiceapplication.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = new(string)
				*_m.RecipientEmail = value.String
			}
		case invoiceapplication.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.String
			}
		case invoiceapplication.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case invoiceapplication.FieldExternalSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field external_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExternalSnapshot); err != nil {
					return fmt.Errorf("unmarshal field external_snapshot: %w", err)
				}
			}
		case invoiceapplication.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case invoiceapplication.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case invoiceapplication.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case invoiceapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case invoiceapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceApplication.
// This includes values selected through modifiers, order, etc.
func (_m *InvoiceApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceApplication.
// Note that you need to call InvoiceApplication.Unwrap() before calling this method if this InvoiceApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvoiceApplication) Update() *InvoiceApplicationUpdateOne {
	return NewInvoiceApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvoiceApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvoiceApplication) Unwrap() *InvoiceApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvoiceApplication) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderIds))
	builder.WriteString(", ")
	builder.WriteString("order_nos=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderNos))
	builder.WriteString(", ")
	builder.WriteString("need_pay_tax=")
	builder.WriteString(fmt.Sprintf("%v", _m.NeedPayTax))
	builder.WriteString(", ")
	builder.WriteString("tax_order_nos=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxOrderNos))
	builder.WriteString(", ")
	builder.WriteString("validation_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidationSnapshot))
	builder.WriteString(", ")
	if v := _m.ExternalID; v != nil {
		builder.WriteString("external_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Title; v != nil {
		builder.WriteString("title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RecipientEmail; v != nil {
		builder.WriteString("recipient_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(_m.TotalAmount)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("external_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalSnapshot))
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceApplications is a parsable slice of InvoiceApplication.
type InvoiceApplications []*InvoiceApplication
