import { mount, flushPromises } from '@vue/test-utils'
import { createRouter, createMemoryHistory } from 'vue-router'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import HelpCenterView from '../HelpCenterView.vue'
import HelpMarkdown from '@/components/help/HelpMarkdown.vue'
import { helpSections } from '@/utils/helpGuide'

const mocks = vi.hoisted(() => ({ copy: vi.fn(), list: vi.fn(), groups: vi.fn(), models: vi.fn(), keys: vi.fn() }))
vi.mock('vue-i18n', async () => ({ ...(await vi.importActual<typeof import('vue-i18n')>('vue-i18n')), useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<div><slot /></div>' } }))
vi.mock('@/composables/useClipboard', () => ({ useClipboard: () => ({ copyToClipboard: mocks.copy }) }))
vi.mock('@/api/helpDocs', () => ({ default: { list: mocks.list } }))
vi.mock('@/api/groups', () => ({ userGroupsAPI: { getAvailable: mocks.groups, getHelpModels: mocks.models } }))
vi.mock('@/api/keys', () => ({ keysAPI: { list: mocks.keys } }))
vi.mock('@/stores/app', () => ({ useAppStore: () => ({ cachedPublicSettings: { api_base_url: 'https://gateway.example', custom_endpoints: [{ name: 'unused', endpoint: 'https://wrong.example' }] }, fetchPublicSettings: vi.fn() }) }))

beforeEach(() => {
  vi.clearAllMocks()
  mocks.models.mockResolvedValue([])
  mocks.keys.mockResolvedValue({ items: [], total: 0, page: 1, page_size: 100, pages: 0 })
  mocks.list.mockResolvedValue([
    { id: 1, slug: 'quick-start', category: 'quick-start', title: 'Start', content_markdown: 'Welcome', summary: '' },
    ...['claude-code', 'codex', 'opencode'].map((category, index) => ({ id: index + 2, slug: 'clients/' + category, category, title: category, summary: '', content_markdown: '## 安装\nInstall\n\n## 认证与项目配置\nConfiguration notes\n\n## 验证与成功判据\nVerify', selector_schema: { clients: [category === 'claude-code' ? 'claude' : category] } }))
  ])
  mocks.groups.mockResolvedValue([{ id: 1, name: 'Claude group', platform: 'anthropic', status: 'active' }, { id: 2, name: 'OpenAI group', platform: 'openai', status: 'active' }, { id: 3, name: 'DeepSeek group', platform: 'deepseek', status: 'active' }])
})

async function page(url: string) {
  const router = createRouter({ history: createMemoryHistory(), routes: [{ path: '/:pathMatch(.*)*', component: HelpCenterView }] })
  // Use the production slug parameter so article selection follows navigation.
  router.addRoute({ path: '/help/:slug(.*)', component: HelpCenterView })
  await router.push(url)
  await router.isReady()
  const wrapper = mount(HelpCenterView, { global: { plugins: [router], stubs: { AppLayout: { template: '<div><slot /></div>' } } } })
  await flushPromises()
  return { wrapper, router }
}

describe('Help center guided setup', () => {

  it('hides retired tutorials and displays v1 regardless of the editing revision', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([
      ...docs.map((doc: Record<string, unknown>) => ({ ...doc, version: 19 })),
      ...['read-frog', 'roo-code'].map(category => ({ id: category, slug: 'clients/' + category, category, title: category, summary: '', content_markdown: 'Retired', selector_schema: {} }))
    ])
    const { wrapper } = await page('/help')
    expect(wrapper.get('.article-footer').text()).toContain('v1')
    expect(wrapper.get('.article-footer').text()).not.toContain('v19')
    expect(wrapper.text()).not.toContain('read-frog')
    expect(wrapper.text()).not.toContain('roo-code')
    wrapper.unmount()
    const retired = await page('/help/clients/read-frog')
    expect(retired.wrapper.text()).toContain('helpCenter.empty')
    expect(retired.wrapper.find('.settings-preview').exists()).toBe(false)
    retired.wrapper.unmount()
  })

  it('shows the API probe for every active group and hides client controls', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, { id: 80, slug: 'api', category: 'api', title: 'API', summary: 'probe', content_markdown: '## 怎么用\nSelect a group' }])
    mocks.models.mockResolvedValue([{ id: 'claude-sonnet' }])
    mocks.keys.mockResolvedValue({ items: [{ id: 9, name: 'primary', key: 'sk-secret-value-1234', group_id: 1, status: 'active' }], total: 1, page: 1, page_size: 100, pages: 1 })
    const { wrapper } = await page('/help/api')
    expect(wrapper.find('.channel-row').exists()).toBe(false)
    expect(wrapper.find('nav.client-row').exists()).toBe(false)
    expect(wrapper.find('.code-call-scene').exists()).toBe(false)
    expect(wrapper.find('.api-probe').exists()).toBe(true)
    expect(wrapper.findAll('#help-api-group option').map(option => option.text())).toEqual(['Claude group', 'OpenAI group', 'DeepSeek group'])
    expect(wrapper.get('.probe-protocols .selected').text()).toBe('helpCenter.probe.messages')
    expect(wrapper.text()).toContain('/v1/messages')
    expect(wrapper.text()).toContain('****1234')
    expect(wrapper.html()).not.toContain('sk-secret-value-1234')
    await wrapper.get('#help-api-group').setValue('2')
    await flushPromises()
    expect(mocks.models).toHaveBeenCalledWith(2, expect.any(AbortSignal))
    expect(mocks.keys).toHaveBeenCalledWith(1, 100, { group_id: 2, status: 'active' }, expect.objectContaining({ signal: expect.any(AbortSignal) }))
    expect(wrapper.get('.probe-protocols .selected').text()).toBe('helpCenter.probe.responses')
    expect(wrapper.text()).toContain('/v1/responses')
    expect(wrapper.html()).not.toContain('sk-secret-value-1234')
    wrapper.unmount()
  })
  it('does not repeat the tutorial title inside the page', async () => {
    const { wrapper } = await page('/help/quick-start')
    expect(wrapper.find('h1').exists()).toBe(false)
    expect(wrapper.text()).not.toContain('helpCenter.title')
    expect(wrapper.text()).toContain('helpCenter.intro')
    wrapper.unmount()
  })
  it('renders the OpenCode terminal in verification with the generated provider and current model', async () => {
    mocks.models.mockResolvedValue([{ id: 'model-example' }])
    const { wrapper } = await page('/help/clients/opencode?platform=openai&group=2')
    expect(wrapper.findAll('.selection-grid label').map(label => label.text())).toEqual(['helpCenter.group', 'helpCenter.model'])
    expect(wrapper.get('#guide-2 .opencode-example').text()).toContain('model-example')
    expect(wrapper.get('.opencode-example').text()).toContain('/models')
    expect(wrapper.find('.claude-terminal-example').exists()).toBe(false)
    wrapper.unmount()
  })
  it('shows the Claude terminal only in Claude verification and follows the selected model', async () => {
    mocks.models.mockResolvedValue([{ id: 'claude-example-2' }, { id: 'claude-example-1' }])
    const { wrapper, router } = await page('/help/clients/claude-code?platform=anthropic&group=1')
    expect(wrapper.get('#guide-2 .claude-terminal-example').text()).toContain('Welcome back!')
    await wrapper.get('#help-model').setValue('claude-example-1')
    expect(wrapper.get('.claude-terminal-example').text()).toContain('claude-example-1')
    await router.push('/help/clients/codex?platform=openai&group=2')
    await flushPromises()
    expect(wrapper.find('.claude-terminal-example').exists()).toBe(false)
    wrapper.unmount()
  })
  it('selects the highest available version and updates model fields without retaining another group model', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, { id: 40, slug: 'clients/workbuddy', category: 'workbuddy', title: 'WorkBuddy', content_markdown: '## 认证与项目配置\nConfigure', selector_schema: { clients: ['workbuddy'] } }])
    mocks.models.mockImplementation((id: number) => Promise.resolve((id === 2 ? ['gpt-5.5', 'gpt-6-astra', 'gpt-image-2'] : ['claude-sonnet-5']).map(id => ({ id }))))
    const { wrapper } = await page('/help/clients/workbuddy?platform=openai&group=2')
    expect((wrapper.get('#help-model').element as HTMLSelectElement).value).toBe('gpt-6-astra')
    expect(wrapper.get('.settings-preview').text()).toContain('gpt-6-astra')
    expect(wrapper.get('.settings-preview').text()).toContain('https://gateway.example/v1/chat/completions')
    expect(wrapper.findAll('.client-logo').length).toBeGreaterThan(1)
    await wrapper.get('#help-model').setValue('gpt-5.5')
    expect(wrapper.get('.settings-preview').text()).toContain('gpt-5.5')
    await wrapper.findAll('.channel-row button').find(b => b.text() === 'Claude')!.trigger('click')
    await flushPromises()
    expect(wrapper.get('.settings-preview').text()).toContain('claude-sonnet-5')
    expect(wrapper.get('.settings-preview').text()).not.toContain('gpt-5.5')
    wrapper.unmount()
  })
  it('renders desktop settings as copyable fields using the default endpoint, with channel restrictions', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, ...['cherry-studio', 'cursor', 'cline', 'roo-code'].map((client, i) => ({ id: 20 + i, slug: 'clients/' + client, category: client, title: client, summary: '', content_markdown: '## 认证与项目配置\nFill settings', selector_schema: { clients: [client] } }))])
    const { wrapper, router } = await page('/help/clients/cherry-studio?platform=anthropic&group=1')
    expect(wrapper.get('.settings-preview').text()).toContain('https://gateway.example')
    expect(wrapper.get('.settings-preview').text()).not.toContain('wrong.example')
    expect(wrapper.get('.settings-preview').text()).toContain('YOUR_MODEL_ID')
    expect(wrapper.findAll('nav.client-row button').some(b => b.text() === 'Cursor')).toBe(false)
    await wrapper.get('button[aria-label="helpCenter.copyConfig API Host"]').trigger('click')
    expect(mocks.copy).toHaveBeenCalledWith('https://gateway.example', 'helpCenter.copied')
    await wrapper.findAll('nav.client-row button').find(b => b.text() === 'Cline')!.trigger('click')
    await flushPromises()
    expect(router.currentRoute.value.path).toBe('/help/clients/cline')
    expect(wrapper.get('.settings-preview').text()).toContain('OpenAI Compatible')
    expect(router.currentRoute.value.fullPath).not.toContain('YOUR_API_KEY')
    wrapper.unmount()
  })
  it('provides channel-to-many-client navigation from the landing page and preserves channel on client changes', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, { id: 9, slug: 'clients/grok-cli', category: 'grok-cli', title: 'Grok CLI', summary: '', content_markdown: '## 安装\nInstall', selector_schema: { clients: ['grok'], platforms: ['grok'] } }])
    const { wrapper, router } = await page('/help')
    expect(wrapper.findAll('.reading-toc a').every(a => a.attributes('href')?.startsWith('#'))).toBe(true)
    await wrapper.findAll('.channel-row button').find(b => b.text() === 'Grok')!.trigger('click')
    await flushPromises()
    expect(wrapper.findAll('nav.client-row button').map(b => b.text())).toEqual(['Grok CLI', 'Claude Code', 'Codex', 'OpenCode'])
    expect(router.currentRoute.value.query.platform).toBe('grok')
    expect(wrapper.get('[role="status"]').text()).toBe('helpCenter.noClientGroup')
    await wrapper.findAll('nav.client-row button').find(b => b.text() === 'Codex')!.trigger('click')
    await flushPromises()
    expect(router.currentRoute.value.path).toBe('/help/clients/codex')
    expect(router.currentRoute.value.query.platform).toBe('grok')
    expect(wrapper.text()).not.toContain('base_url =')
    await wrapper.findAll('.channel-row button').find(b => b.text() === 'OpenAI')!.trigger('click')
    await flushPromises()
    expect(wrapper.findAll('nav.client-row button').map(b => b.text())).toEqual(['Codex', 'OpenCode'])
    expect(wrapper.text()).toContain('base_url =')
    router.back()
    await flushPromises()
    expect(router.currentRoute.value.query.platform).toBe('grok')
    expect(wrapper.text()).not.toContain('base_url =')
    wrapper.unmount()
  })
  it('keeps the channel browser usable without any groups and respects document channel restrictions', async () => {
    mocks.groups.mockResolvedValue([])
    const docs = await mocks.list()
    docs.find((d: { category: string }) => d.category === 'opencode').selector_schema = { clients: ['opencode'], platforms: ['openai'] }
    mocks.list.mockResolvedValue(docs)
    const { wrapper } = await page('/help/clients/codex?platform=anthropic')
    expect(wrapper.findAll('.channel-row button').length).toBeGreaterThan(1)
    expect(wrapper.findAll('nav.client-row button').map(b => b.text())).toEqual(['Claude Code', 'Codex'])
    expect(wrapper.get('[role="status"]').text()).toBe('helpCenter.noClientGroup')
    wrapper.unmount()
  })
  it('keeps SillyTavern and TavernAI on the tavern channel and lists chat-completion groups', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, ...['sillytavern', 'tavernai'].map((client, index) => ({ id: 50 + index, slug: 'clients/' + client, category: client, title: client, summary: '', content_markdown: '## 认证与项目配置\nFill settings', selector_schema: { clients: [client], platforms: ['tavern'] } }))])
    mocks.groups.mockResolvedValue([
      { id: 1, name: 'Claude group', platform: 'anthropic', status: 'active', claude_code_only: true },
      { id: 2, name: 'OpenAI group', platform: 'openai', status: 'active' },
      { id: 3, name: 'DeepSeek group', platform: 'deepseek', status: 'active' }
    ])
    const { wrapper } = await page('/help/clients/sillytavern?platform=openai&group=1')
    expect(wrapper.findAll('.channel-row button').map(button => button.text())).toContain('helpCenter.tavernChannel')
    expect(wrapper.findAll('nav.client-row button').map(button => button.text())).toEqual(['SillyTavern', 'TavernAI'])
    expect(wrapper.get('.channel-row .selected').text()).toBe('helpCenter.tavernChannel')
    const groups = wrapper.findAll('#help-group option').map(option => option.text())
    expect(groups).toEqual(['OpenAI group', 'DeepSeek group'])
    expect(wrapper.get('.settings-preview').text()).toContain('https://gateway.example/v1')
    expect(wrapper.get('.settings-preview').text()).not.toContain('https://gateway.example/v1/chat/completions')
    await wrapper.findAll('.channel-row button').find(button => button.text() === 'OpenAI')!.trigger('click')
    await flushPromises()
    expect(wrapper.findAll('nav.client-row button').map(button => button.text())).not.toContain('SillyTavern')
    wrapper.unmount()
  })
  it('omits domestic model platforms from the help center channel selector', async () => {
    const { wrapper } = await page('/help')
    const channelLabels = wrapper.findAll('.channel-row button').map(button => button.text())
    expect(channelLabels).not.toContain('DeepSeek')
    expect(channelLabels).not.toContain('MiniMax')
    expect(channelLabels).not.toContain('Kimi')
    expect(channelLabels).not.toContain('智谱 GLM')
    expect(wrapper.text()).not.toContain('helpCenter.domesticChannel')
    wrapper.unmount()
  })
  it('normalizes shared links that still target a removed domestic channel', async () => {
    const { wrapper, router } = await page('/help/clients/codex?platform=deepseek&group=3')
    await flushPromises()
    expect(wrapper.findAll('.channel-row button').some(button => button.attributes('aria-pressed') === 'true' && button.text() === 'DeepSeek')).toBe(false)
    expect(router.currentRoute.value.query.platform).not.toBe('deepseek')
    wrapper.unmount()
  })
  it('shows Grok documentation without a Grok group but does not generate unsupported credentials', async () => {
    const docs = await mocks.list()
    mocks.list.mockResolvedValue([...docs, { id: 9, slug: 'clients/grok-cli', category: 'grok-cli', title: 'Grok CLI', summary: 'Official Grok Build', content_markdown: '## 安装\nInstall Grok\n\n## 认证与项目配置\nConfigure Grok', selector_schema: { clients: ['grok'], platforms: ['grok'] } }])
    const { wrapper, router } = await page('/help')
    const link = wrapper.findAll('.client-directory a').find(a => a.text().includes('Grok CLI'))
    expect(link).toBeDefined()
    await router.push(link!.attributes('href'))
    await flushPromises()
    expect(wrapper.get('.article-heading h2').text()).toBe('Grok CLI')
    expect(wrapper.get('[role="status"]').text()).toBe('helpCenter.noClientGroup')
    expect(wrapper.text()).not.toContain('XAI_API_KEY=')
    expect(wrapper.text()).toContain('https://x.ai/cli/install.sh')
    wrapper.unmount()
  })
  it('switches both the article and configuration with the client', async () => {
    const { wrapper, router } = await page('/help/clients/claude-code?group=1&platform=anthropic')
    expect(wrapper.text()).toContain('ANTHROPIC_BASE_URL')
    await wrapper.findAll('button').find(button => button.text() === 'Codex')!.trigger('click')
    await flushPromises()
    expect(router.currentRoute.value.path).toBe('/help/clients/codex')
    expect(wrapper.get('.article-heading h2').text()).toBe('codex')
    expect(wrapper.text()).toContain('wire_api = "responses"')
    expect(wrapper.text()).not.toContain('ANTHROPIC_BASE_URL')
    wrapper.unmount()
  })
  it('restores Windows and uses only the site endpoint, stripping endpoint and key parameters on selection', async () => {
    const { wrapper, router } = await page('/help/clients/claude-code?group=1&platform=anthropic&os=windows&shell=powershell&endpoint=1&api_key=secret')
    expect(wrapper.text()).toContain('install.ps1')
    expect(wrapper.text()).toContain('settings.json')
    await wrapper.findAll('button').find(button => button.text() === 'helpCenter.temporaryConfig')!.trigger('click')
    expect(wrapper.text()).toContain('$env:ANTHROPIC_BASE_URL="https://gateway.example"')
    expect(wrapper.text()).not.toContain('wrong.example')
    expect(wrapper.text()).not.toContain('helpCenter.endpoint')
    await wrapper.findAll('button').find(button => button.text() === 'Linux')!.trigger('click')
    await flushPromises()
    expect(router.currentRoute.value.query).not.toHaveProperty('endpoint')
    expect(router.currentRoute.value.query).not.toHaveProperty('api_key')
    expect(wrapper.text()).toContain('install.sh')
    wrapper.unmount()
  })
  it('places one copy button at the original code block and copies exact text', async () => {
    const wrapper = mount(HelpMarkdown, { props: { content: 'Before\n\n```sh\necho OK\n```\n\nAfter', showToc: false } })
    expect(wrapper.findAll('pre')).toHaveLength(1)
    await wrapper.get('button').trigger('click')
    expect(mocks.copy).toHaveBeenCalledWith('echo OK\n', 'helpCenter.copied')
    expect(wrapper.text().indexOf('Before')).toBeLessThan(wrapper.text().indexOf('echo OK'))
    expect(wrapper.text().indexOf('After')).toBeGreaterThan(wrapper.text().indexOf('echo OK'))
  })
  it('does not split headings inside fenced code into steps', () => {
    expect(helpSections('## Install\n```sh\n## Not a section\n```\n## Verify\nOK')).toHaveLength(2)
  })
})
