<template>
  <div class="client-specific-guide dsh-guide" data-guide="dsh">
    <GuideStep :number="1" id="custom-api" :title="t('helpCenter.specific.dshCustom')" :description="t('helpCenter.specific.dshCustomHint')"><div class="guide-screen"><div class="screen-top"><strong>Settings / Models</strong><span>＋ Add model provider</span></div><div class="screen-body"><div class="provider-tabs"><span>Third-party model provider</span><strong>Custom model API</strong></div><HelpSettingField :field="field('Provider ID')" /><HelpSettingField :field="field('Base URL')" /><HelpSettingField :field="field('API')" label="API protocol" choice /><HelpSettingField :field="field('API Key')" /><p class="screen-hint">{{ t('helpCenter.specific.dshCredential') }}</p></div></div></GuideStep>
    <GuideStep :number="2" id="catalog-save" :title="t('helpCenter.specific.dshCatalog')" :description="t('helpCenter.specific.dshCatalogHint')"><div class="guide-screen"><div class="screen-top"><strong>Model catalog</strong><span class="illustrated-action">Fetch available models</span></div><div class="screen-body"><div class="screen-value">{{ t('helpCenter.scenes.searchModels') }}</div><HelpSettingField v-if="modelField" :field="modelField" /><div class="inline-model"><span>✓</span><code>{{ model }}</code><span>Add selected</span></div><p class="screen-hint">{{ t('helpCenter.scenes.capabilities') }}</p></div><div class="screen-bottom"><span class="illustrated-action illustrated-primary">Create provider</span></div></div></GuideStep>
    <GuideStep :number="3" id="new-session" :title="t('helpCenter.specific.dshSession')" :description="t('helpCenter.specific.dshSessionHint')"><div class="guide-screen"><div class="screen-top"><strong>dsh</strong><span>＋ New session</span></div><div class="screen-body"><div class="dsh-session"><span>{{ t('helpCenter.walkthrough.inClient') }}</span><div class="inline-model"><strong>site</strong><code>{{ model }}</code><span>⌄ ↑</span></div></div></div></div></GuideStep>
    <GuideStep :number="4" id="reasoning-level" :title="t('helpCenter.specific.dshReasoning')" :description="t('helpCenter.specific.dshReasoningHint')"><div class="guide-screen"><div class="screen-top"><strong>Model capabilities</strong><span>Advanced</span></div><div class="screen-body"><div class="reasoning-row"><span>Reasoning effort</span><div class="reasoning-options"><span>low</span><span class="selected">medium</span><span>high</span><span>xhigh</span></div></div><p class="screen-hint">Do not add this menu unless the selected model and gateway support reasoning efforts.</p></div></div></GuideStep>
  </div>
</template>
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import GuideStep from './GuideStep.vue'
import HelpSettingField from '../HelpSettingField.vue'
import { useGuideFields, type ClientGuideProps } from './guideFields'
const props = defineProps<ClientGuideProps>(); const { t } = useI18n(); const { field, model, modelField } = useGuideFields(props)
</script>
<style scoped>.provider-tabs { display: flex; gap: .5rem; flex-wrap: wrap; border-bottom: 1px solid var(--scene-line); padding-bottom: .7rem; }.provider-tabs > * { padding: .5rem; }.provider-tabs strong { color: var(--client-accent-ink, #93c5fd); border-bottom: 2px solid #3765cd; }.dsh-session { padding: 1rem; border: 1px solid var(--scene-line); border-radius: 8px; }.dsh-session > .inline-model { margin-top: 2rem; }.reasoning-row { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: .8rem; border: 1px solid var(--scene-line); border-radius: 8px; }.reasoning-options { display: flex; gap: .35rem; flex-wrap: wrap; }.reasoning-options span { padding: .35rem .55rem; border: 1px solid var(--scene-line); border-radius: 5px; font-size: .7rem; }.reasoning-options .selected { color: #fff; border-color: #3765cd; background: #3765cd; } @media (max-width: 540px) { .reasoning-row { align-items: flex-start; flex-direction: column; } }</style>
