// Code generated by ent, DO NOT EDIT.

package helpdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldID, id))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldSlug, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldTitle, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldCategory, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldSummary, v))
}

// ContentMarkdown applies equality check predicate on the "content_markdown" field. It's identical to ContentMarkdownEQ.
func ContentMarkdown(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldContentMarkdown, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldStatus, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldVersion, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldPublishedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldSlug, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldTitle, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldCategory, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldSummary, v))
}

// ContentMarkdownEQ applies the EQ predicate on the "content_markdown" field.
func ContentMarkdownEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldContentMarkdown, v))
}

// ContentMarkdownNEQ applies the NEQ predicate on the "content_markdown" field.
func ContentMarkdownNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldContentMarkdown, v))
}

// ContentMarkdownIn applies the In predicate on the "content_markdown" field.
func ContentMarkdownIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldContentMarkdown, vs...))
}

// ContentMarkdownNotIn applies the NotIn predicate on the "content_markdown" field.
func ContentMarkdownNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldContentMarkdown, vs...))
}

// ContentMarkdownGT applies the GT predicate on the "content_markdown" field.
func ContentMarkdownGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldContentMarkdown, v))
}

// ContentMarkdownGTE applies the GTE predicate on the "content_markdown" field.
func ContentMarkdownGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldContentMarkdown, v))
}

// ContentMarkdownLT applies the LT predicate on the "content_markdown" field.
func ContentMarkdownLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldContentMarkdown, v))
}

// ContentMarkdownLTE applies the LTE predicate on the "content_markdown" field.
func ContentMarkdownLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldContentMarkdown, v))
}

// ContentMarkdownContains applies the Contains predicate on the "content_markdown" field.
func ContentMarkdownContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldContentMarkdown, v))
}

// ContentMarkdownHasPrefix applies the HasPrefix predicate on the "content_markdown" field.
func ContentMarkdownHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldContentMarkdown, v))
}

// ContentMarkdownHasSuffix applies the HasSuffix predicate on the "content_markdown" field.
func ContentMarkdownHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldContentMarkdown, v))
}

// ContentMarkdownEqualFold applies the EqualFold predicate on the "content_markdown" field.
func ContentMarkdownEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldContentMarkdown, v))
}

// ContentMarkdownContainsFold applies the ContainsFold predicate on the "content_markdown" field.
func ContentMarkdownContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldContentMarkdown, v))
}

// SelectorSchemaIsNil applies the IsNil predicate on the "selector_schema" field.
func SelectorSchemaIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldSelectorSchema))
}

// SelectorSchemaNotNil applies the NotNil predicate on the "selector_schema" field.
func SelectorSchemaNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldSelectorSchema))
}

// PublishedSnapshotIsNil applies the IsNil predicate on the "published_snapshot" field.
func PublishedSnapshotIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldPublishedSnapshot))
}

// PublishedSnapshotNotNil applies the NotNil predicate on the "published_snapshot" field.
func PublishedSnapshotNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldPublishedSnapshot))
}

// PublicationHistoryIsNil applies the IsNil predicate on the "publication_history" field.
func PublicationHistoryIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldPublicationHistory))
}

// PublicationHistoryNotNil applies the NotNil predicate on the "publication_history" field.
func PublicationHistoryNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldPublicationHistory))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldContainsFold(FieldStatus, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldVersion, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldPublishedAt))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotNull(FieldUpdatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.HelpDocument {
	return predicate.HelpDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HelpDocument) predicate.HelpDocument {
	return predicate.HelpDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HelpDocument) predicate.HelpDocument {
	return predicate.HelpDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HelpDocument) predicate.HelpDocument {
	return predicate.HelpDocument(sql.NotPredicates(p))
}
